// targets/vue-target-app/src/App.vue
<template>
  <vanilla-ds-button @click="changeText">
    {{ text }}
  </vanilla-ds-button>
</template>

<script>
import 'vanilla-ds/build/vanilla-ds'

export default {
  name: 'App',
  data() {
    return { text: 'Ahoy!' };
  },
  methods: {
    changeText() { this.text = 'You clicked me!'; }
  }
}
</script>

// targets/angular-target-app/src/app/app.component.ts
import { Component } from '@angular/core';
import 'vanilla-ds/build/vanilla-ds';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  text = 'Ahoy!';

  onClick() {
    this.text = 'You clicked me!';
  }
}

<vanilla-ds-button (click)="onClick()">
  {{ text }}
</vanilla-ds-button>
