// targets/vue-target-app/src/VanillaDS/MultiType.vue
<template>
  <vanilla-ds-multitype
    v-bind:title="title"
    v-bind:itemlist="itemList"
  >
    <vanilla-ds-button slot="button"></vanilla-ds-button>
  </vanilla-ds-multitype>
</template>

<script>
export default {
  name: 'VanillaDSMultiType',
  data() {
    return {
      title: 'Multitype component',
      itemList: ['pizza', 'potato', 'banana'],
    };
  },
}
</script>

// targets/react-target-app/src/LitElementDS/MultiType.jsx
import React from 'react';
const DefaultMultiType = () => (
  <litelement-ds-multitype
    title="Multitype component (default button)"
    itemlist={JSON.stringify(['red', 'blue', 'green', 'yellow'])}
    buttonprops={JSON.stringify({ collapsedText: "expandir", expandedText: "recolher" })}
  >
  </litelement-ds-multitype>
);

const MultiType = () => (
  <litelement-ds-multitype
    title="Multitype component"
    itemlist={JSON.stringify(['pizza', 'potato', 'banana'])}
  >
    <litelement-ds-button slot="button"></litelement-ds-button>
  </litelement-ds-multitype>
);

export { DefaultMultiType, MultiType };
