// targets/vue-target-app/src/VanillaDS/MultiType.vue
<template>
  <vanilla-ds-multitype
    v-bind:title="title"
    v-bind:itemlist="itemList"
  >
    <vanilla-ds-button slot="button"></vanilla-ds-button>
  </vanilla-ds-multitype>
</template>

<script>
export default {
  name: 'VanillaDSMultiType',
  data() {
    return {
      title: 'Multitype component',
      itemList: ['pizza', 'potato', 'banana'],
    };
  },
}
</script>

// targets/react-target-app/src/VanillaDS/MultiType.jsx
import React from 'react';
const DefaultMultiType = () => (
  <vanilla-ds-multitype
    title="Multitype component (default button)"
    itemlist={['red', 'blue', 'green', 'yellow']}
    buttonprops={JSON.stringify({ collapsedText: "expandir", expandedText: "recolher" })}
  >
  </vanilla-ds-multitype>
);

const MultiType = () => (
  <vanilla-ds-multitype
    title="Multitype component"
    itemlist={['pizza', 'potato', 'banana']}
  >
    <vanilla-ds-button slot="button"></vanilla-ds-button>
  </vanilla-ds-multitype>
);

export { DefaultMultiType, MultiType };
