// targets/vue-target-app/src/VanillaDS/Button.vue
<template>
  <vanilla-ds-button @click="changeText">
    {{ text }}
  </vanilla-ds-button>
</template>

<script>
import 'vanilla-ds/build/vanilla-ds'

export default {
  name: 'VanillaDSButton',
  data() {
    return { text: 'Ahoy!' };
  },
  methods: {
    changeText() { this.text = 'You clicked me!'; }
  }
}
</script>

// targets/angular-target-app/src/app/LitElementDS/button.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'litelement-button',
  templateUrl: './button.component.html',
})

export class LitElementDSButton {
  text = 'Ahoy!';

  onClick() {
    this.text = 'You clicked me!';
  }
}

<litelement-ds-button (click)="onClick()">
  {{ text }}
</litelement-ds-button>
