// targets/react-target-app/src/VanillaDS/Button.jsx
import React, { useState } from 'react';
import 'vanilla-ds/build/vanilla-ds';

const VanillaDSButton = () => {
  const [label, setLabel] = useState('Ahoy!');

  return (
    <vanilla-ds-button onClick={() => setLabel('You clicked me!')}>
      {label}
    </vanilla-ds-button>
  );
};

export default VanillaDSButton;

// targets/vue-target-app/src/VanillaDS/Button.vue
<template>
  <vanilla-ds-button @click="changeText">
    {{ text }}
  </vanilla-ds-button>
</template>

<script>
import 'vanilla-ds/build/vanilla-ds'

export default {
  name: 'VanillaDSButton',
  data() {
    return { text: 'Ahoy!' };
  },
  methods: {
    changeText() { this.text = 'You clicked me!'; }
  }
}
</script>
