// targets/angular-target-app/src/app/VanillaDS/multitype.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'vanilla-multitype',
  templateUrl: './multitype.component.html',
})

export class VanillaDSMultiType {
  title = "Multitype component";
  itemList = ['pizza', 'potato', 'banana'];
}

<vanilla-ds-multitype
  [attr.title]="title"
  [attr.itemlist]="itemList"
>
  <vanilla-ds-button slot="button"></vanilla-ds-button>
</vanilla-ds-multitype>

// targets/vue-target-app/src/VanillaDS/MultiType.vue
<template>
  <vanilla-ds-multitype
    v-bind:title="title"
    v-bind:itemlist="itemList"
  >
    <vanilla-ds-button slot="button"></vanilla-ds-button>
  </vanilla-ds-multitype>
</template>

<script>
export default {
  name: 'VanillaDSMultiType',
  data() {
    return {
      title: 'Multitype component',
      itemList: ['pizza', 'potato', 'banana'],
    };
  },
}
</script>
