// targets/vue-target-app/src/VanillaDS/DefaultMultiType.vue
<template>
  <vanilla-ds-multitype
    v-bind:title="title"
    v-bind:itemlist="itemList"
    v-bind:buttonprops="buttonProps"
  >
  </vanilla-ds-multitype>
</template>

<script>
export default {
  name: 'VanillaDSDefaultMultiType',
  data() {
    return {
      title: 'Multitype component (default button)',
      itemList: ['red', 'blue', 'green', 'yellow'],
      buttonProps: JSON.stringify({ collapsedText: "expandir", expandedText: "recolher" }),
    };
  },
}
</script>

// targets/angular-target-app/src/app/VanillaDS/defaultmultitype.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'vanilla-defaultmultitype',
  templateUrl: './defaultmultitype.component.html',
})

export class VanillaDSDefaultMultiType {
  title = "Multitype component (default button)";
  itemList = ['red', 'blue', 'green', 'yellow'];
  buttonProps = JSON.stringify({ collapsedText: "expandir", expandedText: "recolher" });
}

<vanilla-ds-multitype
  [attr.title]="title"
  [attr.itemlist]="itemList"
  [attr.buttonprops]="buttonProps"
>
</vanilla-ds-multitype>
